[project]
title = "Global Happiness Explorer"
version = "0.1.0"
port = 8501
slug = "global-happiness-explorer"  
entrypoint = "app.py"    

[branding]
name = "Global Happiness Explorer"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.World-happiness-report-updated_2024] 
type = "csv"
path = "data/World-happiness-report-updated_2024.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
